export const TEXT_CHANGED = 'TEXT_CHANGED';
export const PASSWORD_TEXT_CHANGED = 'PASSWORD_TEXT_CHANGED';
export const SAVE_USERNAME_AND_USERTYPE = 'SAVE_USERNAME_AND_USERTYPE';
export const QUERY_CHANGED = 'QUERY_CHANGED';
export const TYPE_CHANGED = 'TYPE_CHANGED';
export const SEARCH = 'SEARCH';
export const SAVE_USERTYPE = 'SAVE_USERTYPE';
export const SAVE ='SAVE';
export const LOGOUT ='LOGOUT';
export const FETCH_PROFILE ='FETCH_PROFILE';
export const BASE_URL = 'http://localhost:4000/api/';//later change this to heroku url
export const LAST_FM_API_KEY = '936c99c515a1eeafd21e0ca253de20d8';
export const LAST_FM_TRACK_INFO_URL = 'http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=API_KEY';
export const LAST_FM_ALBUM_INFO_URL = 'http://ws.audioscrobbler.com/2.0/?method=album.getInfo&api_key=API_KEY';
export const LAST_FM_ARTIST_INFO_URL = 'http://ws.audioscrobbler.com/2.0/?method=artist.getInfo&api_key=API_KEY';
export const SET_DETAILS = 'SET_DETAILS';
export const TOGGLE = 'TOGGLE';
export const ALL_EVENTS_FOR_USER = 'ALL_EVENTS_FOR_USER';
export const ADMIN_SAVE_USERS = 'ADMIN_SAVE_USERS';
export const ALL_PLAYLIST_FOR_USER = 'ALL_PLAYLIST_FOR_USER';
export const TRACKS_IN_PLAYLIST = 'TRACKS_IN_PLAYLIST';
export const FETCH_LIKED_ITEMS = 'FETCH_LIKED_ITEMS';
export const ARTISTS_IN_EVENT = 'ARTISTS_IN_EVENT';
export const TOGGLE_PLAYLIST = 'TOGGLE_PLAYLIST';
export const TOGGLE_EVENT = 'TOGGLE_EVENT';
export const FETCH_RECOMMENDED_ITEMS = 'FETCH_RECOMMENDED_ITEMS';
export const ALL_LIKED_ALBUM = 'ALL_LIKED_ALBUM';
export const ALL_LIKED_TRACK = 'ALL_LIKED_TRACK';
export const ALL_RECOMMENDED_ALBUM = 'ALL_RECOMMENDED_ALBUM';
export const ALL_RECOMMENDED_TRACK= 'ALL_RECOMMENDED_TRACK';
export const AUDIOPHILE_RESULTS ='AUDIOPHILE_RESULTS';
export const OPEN_AUDIOPHILE_DETAILS ='OPEN_AUDIOPHILE_DETAILS';
export const CLOSE_AUDIOPHILE_DETAILS ='CLOSE_AUDIOPHILE_DETAILS';
export const AUDIOPHILE_RECOMMEND_RESULTS ='AUDIOPHILE_RECOMMEND_RESULTS';
export const EVENTS_NEAR_USER ='EVENTS_NEAR_USER';
export const DROP_SEARCH_RESULT ='DROP_SEARCH_RESULT';